load("//learning/gemini/agents/skill_rules:skills.bzl", "agent_skill")

package(default_visibility = ["//learning/gemini/agents/skills:__subpackages__"])

agent_skill(
    name = "gke_tpu_dynamic_slices_monitoring",
    srcs = ["SKILL.md"],
)
