load("//learning/gemini/agents/skill_rules:skills.bzl", "agent_skill")

package(default_visibility = ["//learning/gemini/agents/skills:__subpackages__"])

agent_skill(
    name = "gke_ai_troubleshooting_jobset_interruption",
    srcs = ["SKILL.md"],
)
